name: Infrastructure Pipeline

on:
  pull_request:
    branches: [main]
    paths:
      - 'terraform/global/**'
      - 'terraform/dev/**'
      - 'terraform/prod/**'
      - 'terraform/scripts/**'
      - 'terraform/k8s-prod/**' 
      - 'terraform/k8s-dev/**'
      - '.github/workflows/infra_pipeline.yml'
  push:
    branches: [main]
    paths:
      - 'terraform/global/**'
      - 'terraform/dev/**'
      - 'terraform/prod/**'
      - 'terraform/scripts/**'
      - 'terraform/k8s-dev/**'
      - 'terraform/k8s-prod/**'  
      - '.github/workflows/infra_pipeline.yml'

permissions:
  contents: read

concurrency:
  group: infra-pipeline-main
  cancel-in-progress: false

jobs:
  global:
    name: Global
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/global

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init GLOBAL
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=global/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate GLOBAL
        run: terraform validate

      - name: Plan GLOBAL
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply GLOBAL
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  dev:
    name: Dev
    needs: global
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init DEV
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=dev/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate DEV
        run: terraform validate

      - name: Plan DEV
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply DEV
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  k8s_dev:
    name: K8s Dev
    needs: dev
    runs-on: [self-hosted, linux, x64, dev-k8s]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/k8s-dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Ensure kubeconfig exists
        run: |
          mkdir -p ~/.kube
          sudo cp /etc/kubernetes/admin.conf ~/.kube/config
          sudo chown $(id -u):$(id -g) ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Init K8S DEV
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=k8s-dev/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate K8S DEV
        run: terraform validate

      - name: Plan K8S DEV
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply K8S DEV
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  prod:
    name: Prod
    needs: k8s_dev
    runs-on: ubuntu-latest
    environment: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init PROD
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=prod/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate PROD
        run: terraform validate

      - name: Plan PROD
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply PROD
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  prod_k8s:   
    name: Prod Kubernetes Workloads

    needs: prod   # runs after prod infra

    runs-on: [self-hosted, linux, x64, prod-k8s]

    environment: prod   # IMPORTANT: requires approval

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/k8s-prod

    steps:

      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init PROD K8S
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=k8s-prod/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate PROD K8S
        run: terraform validate
      
      - name: Plan PROD
        if: github.event_name == 'pull_request'   #plan runs  on PR
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply PROD
        if: github.event_name == 'push'       #apply only after merge+approval
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
