name: Amar Dev Labs Workflow

on:
  workflow_dispatch:
  
   pull_request:
    branches: [main]
    paths:
      - 'terraform/global/**'
      - 'terraform/dev/**'
      - 'terraform/prod/**'
      - 'terraform/scripts/**'
      - 'terraform/k8s-dev/**'
      - 'terraform/k8s-prod/**'
      - 'terraform/o11y-prod/**'
      - '.github/workflows/infra_pipeline.yml'
  
on:
   workflow_dispatch:     
   push:
    branches: [main]
    paths:
      - 'terraform/global/**'
      - 'terraform/dev/**'
      - 'terraform/prod/**'
      - 'terraform/scripts/**'
      - 'terraform/k8s-dev/**'
      - 'terraform/k8s-prod/**'
      - '.github/workflows/infra_pipeline.yml'
      - 'terraform/o11y-prod/**'

permissions:
  contents: read

concurrency:
  group: infra-pipeline-main
  cancel-in-progress: false

jobs:
  global:
    name: Global
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/global

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init GLOBAL
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=global/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate GLOBAL
        run: terraform validate

      - name: Plan GLOBAL
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply GLOBAL
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  dev:
    name: Dev
    needs: global
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init DEV
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=dev/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate DEV
        run: terraform validate

      - name: Plan DEV
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply DEV
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  k8s_dev:
    name: K8s Dev
    needs: dev
    runs-on: [self-hosted, Linux, X64, dev-k8s]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/k8s-dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Ensure kubeconfig exists
        run: |
          mkdir -p ~/.kube
          sudo cp /etc/kubernetes/admin.conf ~/.kube/config
          sudo chown $(id -u):$(id -g) ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Init K8S DEV
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=k8s-dev/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate K8S DEV
        run: terraform validate

      - name: Plan K8S DEV
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply K8S DEV
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  prod_plan:
    name: Prod Plan
    needs: k8s_dev
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
  
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init PROD
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=prod/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate PROD
        run: terraform validate

      - name: Plan PROD
        run: terraform plan -var-file="terraform.tfvars"

  prod_apply:
    name: Prod Apply
    needs: prod_k8s_plan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init PROD
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=prod/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate PROD
        run: terraform validate

      - name: Apply PROD
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  prod_k8s_plan:
    name: Prod Kubernetes Plan
    needs: prod_plan
    runs-on: [self-hosted, Linux, X64, prod-k8s]
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/k8s-prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init PROD K8S
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=k8s-prod/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate PROD K8S
        run: terraform validate

      - name: Plan PROD K8S
        run: terraform plan -var-file="terraform.tfvars"

  prod_k8s_apply:
    name: Prod Kubernetes Workloads
    needs: prod_apply
    runs-on: [self-hosted, Linux, X64, prod-k8s]
    if: github.event_name == 'push'
    environment: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/k8s-prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init PROD K8S
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=k8s-prod/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate PROD K8S
        run: terraform validate

      - name: Apply PROD K8S
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  o11y-plan-pr:
    name: O11Y Plan PR
    needs: prod_plan   
    if: github.event_name == 'pull_request'
    runs-on: [self-hosted, prod-k8s]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/o11y-prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=o11y-prod/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

  o11y-plan-main:
    name: O11Y Plan Main
    needs: prod_plan  
    if: github.event_name == 'push'
    runs-on: [self-hosted, prod-k8s]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/o11y-prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=o11y-prod/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: o11y-prod-tfplan
          path: terraform/o11y-prod/tfplan   
  
  o11y-apply:
    name: O11Y Apply
    needs: 
       - o11y-plan-main
       - prod_apply
       - prod_k8s_apply  
    if: github.event_name == 'push'
    runs-on: [self-hosted, prod-k8s]
    environment: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/o11y-prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=o11y-prod/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: o11y-prod-tfplan
          path: terraform/o11y-prod  

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
