name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

# DEV
      - name: Terraform Init DEV
        run: terraform init -reconfigure -backend-config="key=devops-project/terraform.tfstate"

      - name: Terraform Apply DEV
        run: terraform apply -auto-approve -var-file="envs/dev/terraform.tfvars"

# PROD
      - name: Terraform Init PROD
        run: terraform init -reconfigure -backend-config="key=devops-project/terraform.tfstate"


      - name: Terraform Apply PROD
        run: terraform apply -auto-approve -var-file="envs/prod/terraform.tfvars"
