name: Terraform Dev Workflow

on:
  pull_request:
    branches: [main]
    paths:
      - 'terraform/dev/**'
      - '.github/workflows/tf_dev.yml'

  push:
    branches: [main]
    paths:
      - 'terraform/dev/**'
      - '.github/workflows/tf_dev.yml'

permissions:
  contents: read

jobs:
  dev:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Init DEV
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=amar-devops-tfstate-2026-001" \
            -backend-config="key=dev/devops-project/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Validate DEV
        run: terraform validate

      - name: Plan DEV
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply DEV
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
