name: Terraform Prod Deployment

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  prod:
    runs-on: ubuntu-latest

    environment: prod   # triggers approval

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    defaults:
      run:
        working-directory: terraform/prod

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Init PROD
        run: |
         terraform init \
          -reconfigure \
          -backend-config="bucket=amar-devops-tfstate-2026-001" \
          -backend-config="key=prod/devops-project/terraform.tfstate" \
          -backend-config="region=ap-south-1" \
          -backend-config="dynamodb_table=terraform-locks"

      - name: Validate PROD
        run: terraform validate

      - name: Plan PROD
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply PROD
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
